INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_FREQUENCYADAPTIVEOFDM frequencyAdaptiveOFDM)

FIND_PATH(
    FREQUENCYADAPTIVEOFDM_INCLUDE_DIRS
    NAMES frequencyAdaptiveOFDM/api.h
    HINTS $ENV{FREQUENCYADAPTIVEOFDM_DIR}/include
        ${PC_FREQUENCYADAPTIVEOFDM_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    FREQUENCYADAPTIVEOFDM_LIBRARIES
    NAMES gnuradio-frequencyAdaptiveOFDM
    HINTS $ENV{FREQUENCYADAPTIVEOFDM_DIR}/lib
        ${PC_FREQUENCYADAPTIVEOFDM_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREQUENCYADAPTIVEOFDM DEFAULT_MSG FREQUENCYADAPTIVEOFDM_LIBRARIES FREQUENCYADAPTIVEOFDM_INCLUDE_DIRS)
MARK_AS_ADVANCED(FREQUENCYADAPTIVEOFDM_LIBRARIES FREQUENCYADAPTIVEOFDM_INCLUDE_DIRS)

