INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_FREQADAPTIVEOFDM freqAdaptiveOFDM)

FIND_PATH(
    FREQADAPTIVEOFDM_INCLUDE_DIRS
    NAMES freqAdaptiveOFDM/api.h
    HINTS $ENV{FREQADAPTIVEOFDM_DIR}/include
        ${PC_FREQADAPTIVEOFDM_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    FREQADAPTIVEOFDM_LIBRARIES
    NAMES gnuradio-freqAdaptiveOFDM
    HINTS $ENV{FREQADAPTIVEOFDM_DIR}/lib
        ${PC_FREQADAPTIVEOFDM_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREQADAPTIVEOFDM DEFAULT_MSG FREQADAPTIVEOFDM_LIBRARIES FREQADAPTIVEOFDM_INCLUDE_DIRS)
MARK_AS_ADVANCED(FREQADAPTIVEOFDM_LIBRARIES FREQADAPTIVEOFDM_INCLUDE_DIRS)

