INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_ADAPTIVEOFDM adaptiveOFDM)

FIND_PATH(
    ADAPTIVEOFDM_INCLUDE_DIRS
    NAMES adaptiveOFDM/api.h
    HINTS $ENV{ADAPTIVEOFDM_DIR}/include
        ${PC_ADAPTIVEOFDM_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    ADAPTIVEOFDM_LIBRARIES
    NAMES gnuradio-adaptiveOFDM
    HINTS $ENV{ADAPTIVEOFDM_DIR}/lib
        ${PC_ADAPTIVEOFDM_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ADAPTIVEOFDM DEFAULT_MSG ADAPTIVEOFDM_LIBRARIES ADAPTIVEOFDM_INCLUDE_DIRS)
MARK_AS_ADVANCED(ADAPTIVEOFDM_LIBRARIES ADAPTIVEOFDM_INCLUDE_DIRS)

